package com.example.rmn.iakfinalproject;

/**
 * Created by rmn on 18/11/17.
 */

public class QuestionList {
    public String category[] = {
            "PHP",
            "PHP",
            "PHP",
            "PHP",
            "PHP",
            "Linux Environment",
            "Linux Environment",
            "Linux Environment",
            "Linux Shell",
            "Linux Shell",
            "C++",
            "C++",
            "C++",
            "C++",
            "C++",
            "C++",
            "C++",
            "Java",
            "Java",
            "Java",
            "Java",
            "Java",
            "Java",
            "Java",
            "Java",
            "Java",
            "Operating System",
            "Operating System",
            "Operating System",
            "Operating System",
            "DBMS",
            "DBMS",
            "DBMS",
            "DBMS",
            "DBMS",
            "DBMS",
            "DBMS",
            "DBMS",
            "DBMS",
            "DBMS",
            "DBMS",
            "DBMS",
            "SQL Injection",
            "SQL Injection",
            "SQL Injection",
            "SQL Injection",
            "Data Structure",
            "Data Structure",
            "Data Structure",
            "Data Structure",
            "Data Structure",   
    };

    public String question[] = {
        "What does PHP stand for?",
        "PHP files have a default file extension of...",
        "Which of the following is not a PHP code editor? ",
        "Which version of PHP introduced Try/catch Exception?",
        "Which of the following php statement/statements will store 111 in variable num?",
        "To increase the response time and throughput, the kernel minimizes the frequency of disk access by keeping a pool of internal data buffer called",
        "Which is the core of the operating system?",
        "Single Unix Specification Version 2 provides enhanced support for ... bit unix",
        "Applications communicate with kernel by using:",
        "Which of the following time stamps need not exist for a file on traditional unix file system",
        "Which of the following correctly declares an array?",
        "Which of the following accesses the seventh element stored in array?",
        "Which of the following gives the memory address of the first element in array?",
        "Choose the incorrect option",
        "Which of the following will not return a value?",
        "What will happen when introduce the interface of classes in a run-time polymorphic hierarchy?",
        "What is the use of clog?",
        "What is the range of short data type in Java?",
        "An expression involving byte, int, and literal numbers is promoted to which of these?",
		"Which of these literals can be contained in float data type variable?",
		"Which of these method of class String is used to remove leading and trailing whitespaces?",
		"What is the value returned by function compareTo() if the invoking string is greater than the string compared?",
		"Which of these keywords is used to define packages in Java?",
		"Which of these is a mechanism for naming and visibility control of a class and its content?",
		"Which of the following is correct way of importing an entire package ‘pkg’?",
		"Which of the following is incorrect statement about packages?",
		"To access the services of operating system, the interface is provided by the",
		"By operating system, the resource management can be done via",
		"If a process fails, most operating system write the error information to a",
		"Which facility dynamically adds probes to a running system, both in user processes and in the kernel?",
		"A relational database consists of a collection of",
		"A ________ in a table represents a relationship among a set of values.",
		"The term _______ is used to refer to a row.",
		"For each attribute of a relation, there is a set of permitted values, called the ________ of that attribute.",
		"Course(course_id,sec_id,semester) \n Here the course_id,sec_id and semester are __________ and course is a _________ .",
		"Which one of the following is used to define the structure of the relation ,deleting relations and relating schemas ?",
		"Which one of the following provides the ability to query information from the database and to insert tuples into, delete tuples from, and modify tuples in the database ?",
		"Create table employee (name varchar ,id integer) \n What type of statement is this ?",
		"To remove a relation from an SQL database, we use the ______ command.",
		"Updates that violate __________ are disallowed .",
		"The ________ clause is used to list the attributes desired in the result of a query.",
		"Insert into employee _____ (1002,Joey,2000); \n In the given query which of the keyword has to be inserted ?",
		"SQL injection is an attack in which _________ code is inserted into strings that are later passed to an instance of SQL Server.",
		"Point out the correct statement :",
		"Which of the stored procedure is used to test SQL injection attack ?",
		"_______________ is time based SQL injection attack.",
		"In a max-heap, element with the greatest key is always in the which node?",
		"What is the complexity of adding an element to the heap.",
		"What is an in-place sorting algorithm?",
		"In the following scenarios, when will you use selection sort?",
		"The given array is arr = {3,4,5,2,1}. The number of iterations in bubble sort and selection sort respectively are,",	
    };

    public String possibleAnswer[][] = {
        {"Personal Home Page","Pretext Hypertext Processor","Preprocessor Home Page"},
        {".html",".php",".xml"},
        {"Notepad","Notepad++","Mobile Legends"},
        {"PHP 4","PHP 5","PHP 5.3"},
        {"int $num = 111;","int mum = 111;","$num = 111;"},
        {"Pooling","Spoofing","Buffer cache"},
        {"Shell","Kernel","Script"},
        {"16","32","64"},
        {"System calls","Shell","Shell script"},
        {"Access time","Modification time","Creation time"},
        {"int array[10];"," int array;","array{10};"},
        {"array[6];","array[7];","array(7);"},
        {"array[0];","array[1];","array;"},
        {"void is used when the function does not return a value","void is also used when the value of a pointer is null","void is a special fundamental type"},
        {"null","void","empty"},
        {"Separation of interface from implementation","Merging of interface from implementation","Separation of interface from debugging"},
        {"Standard logging stream","Error stream","Input stream"},
        {"-128 to 127","-32768 to 32767","-2147483648 to 2147483647"},
        {"int","float","long"},
        {"-1.7e+308","-3.4e+038","+1.7e+308"},
        {"startsWith()","trim()","doTrim()"},
        {"zero","value less than zero","value greater than zero"},
        {"pkg","package","Package"},
        {"Object","Packages","Interfaces"},
        {"import pkg.","import pkg.*","Import pkg.*"},
        {"Package defines a namespace in which classes are stored.","A package can contain other package within it.","A package can be renamed without renaming the directory in which the classes are stored."},
        {"System calls","API","Library"},
        {"Time division multiplexing","Space division multiplexing","Both"},
        {"log file","another running process","new file"},
        {"DTrace","DLocate","DMap"},
        {"Tables","Fields","Records"},
        {"Column","Key","Row"},
        {"Attribute","Tuple","Field"},
        {"Domain","Relation","Schema"},
        {"Relations, Attribute","Attributes, Relation","Tuple, Relation"},
        {"DML(Data Manipulation Language)","DDL(Data Definition Language)","Query"},
        {"DML(Data Manipulation Language)","DDL(Data Definition Language)","Query"},
        {"DML","DDL","View"},
        {"Delete","Remove","Drop table"},
        {"Integrity constraints","Authorization","DDL constraints"},
        {"Where","Select","From"},
        {"Table","Values","Relation"},
        {"malicious","redundant","clean"},
        {"Parameterized data cannot be manipulated by a skilled and determined attacker","Procedure that constructs SQL statements should be reviewed for injection vulnerabilities","The primary form of SQL injection consists of indirect insertion of code"},
		{"xp_write","xp_regwrite","xp_reg"},
		{"Initial Exploitation","Blind SQL Injection","Quick detection"},
		{"Leaf node","First node of left sub tree","Root node"},
		{"O(log n)","O(h)","Both above"},
		{"It needs O(1) or O(logn) memory to create auxiliary locations","The input is already sorted and in-place","It requires additional storage"},
		{"The input is already sorted","A large file has to be sorted","Large values need to be sorted with small keys"},
		{"5 and 4","4 and 5","2 and 4"},
    };

    public String answer[] = {
        "Personal Home Page",
        ".php",
        "Mobile Legends",
        "PHP 5",
        "$num = 111;",
        "Buffer cache",
        "Kernel",
        "64",
        "System calls",
        "Creation time",
        "int array[10];",	
        "array[6];",
        "array;",
        "void is also used when the value of a pointer is null",
        "void",
        "Separation of interface from implementation",
        "Standard logging stream",
        "-32768 to 32767",
        "int",
        "-3.4e+038",
        "trim()",
        "value greater than zero",
        "package",
        "Packages",
        "import pkg.*",
        "A package can be renamed without renaming the directory in which the classes are stored.",
        "System calls",
        "Both",
        "log file",
        "DTrace",
        "Tables",
        "Row",
        "Tuple",
        "Domain",
        "Attributes, Relation",
        "DDL(Data Definition Language)",
        "DML(Data Manipulation Language)",
        "DDL",
        "Drop table",
        "Integrity constraints",
        "Select",
        "Values",
        "malicious",
        "Procedure that constructs SQL statements should be reviewed for injection vulnerabilities",
        "xp_regwrite",
        "Blind SQL Injection",
        "Root node",
        "Both above",
        "It needs O(1) or O(logn) memory to create auxiliary locations",
        "Large values need to be sorted with small keys",
        "5 and 4",                    
    };

    public String getCategory(int x){
        String category2 = category[x];
        return category2;
    }
    public String getQuestion(int x){
        String question2 = question[x];
        return question2;
    }

    public String getOption1(int x){
        String option1 = possibleAnswer[x][0];
        return option1;
    }
    public String getOption2(int x){
        String option2 = possibleAnswer[x][1];
        return option2;
    }
    public String getOption3(int x){
        String option3 = possibleAnswer[x][2];
        return option3;
    }

    public String getAnswer(int x){
        String answer2 = answer[x];
        return answer2;
    }
}
